"""add phone_number index

Revision ID: eb39b399164a
Revises: e93976c5a846
Create Date: 2025-12-29 17:28:52.555282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb39b399164a"
down_revision: Union[str, Sequence[str], None] = "e93976c5a846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_phone_number"), "users", type_="unique")
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.create_unique_constraint(
        op.f("uq_users_phone_number"),
        "users",
        ["phone_number"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
