"""add phone_number Unique

Revision ID: e93976c5a846
Revises: 2dc8ec7662eb
Create Date: 2025-12-29 16:49:33.420296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e93976c5a846"
down_revision: Union[str, Sequence[str], None] = "2dc8ec7662eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_phone_number"), "users", ["phone_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_phone_number"), "users", type_="unique")
    # ### end Alembic commands ###
