"""create DeletedArticleCategoryAssociation table

Revision ID: ab2e7c054ffc
Revises: bf2855b7665e
Create Date: 2026-01-16 16:13:42.835944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab2e7c054ffc"
down_revision: Union[str, Sequence[str], None] = "bf2855b7665e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deleted_article_category_associations",
        sa.Column("deleted_article_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f(
                "fk_deleted_article_category_associations_category_id_categories"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_article_id"],
            ["deleted_articles.id"],
            name=op.f(
                "fk_deleted_article_category_associations_deleted_article_id_deleted_articles"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "deleted_article_id",
            "category_id",
            name=op.f("pk_deleted_article_category_associations"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deleted_article_category_associations")
    # ### end Alembic commands ###
