"""create Category table

Revision ID: bf2855b7665e
Revises: 81c386e70db3
Create Date: 2026-01-16 15:07:15.899487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf2855b7665e"
down_revision: Union[str, Sequence[str], None] = "81c386e70db3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "article_category_associations",
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_category_associations_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f(
                "fk_article_category_associations_category_id_categories"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "article_id",
            "category_id",
            name=op.f("pk_article_category_associations"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article_category_associations")
    op.drop_table("categories")
    # ### end Alembic commands ###
